### ISSUE TITLE
Add .editorconfig file to the project

### ISSUE THREAD

**Issue by themaxsandelin** [Niklasson89/PingPong#20]
To make sure everyone is using the same coding style to avoid file system problems and formatting issues I suggest you guys add an .editorconfig file. 🙂

Check it out right here: http://editorconfig.org/

**Comment by themaxsandelin** [comment]
@kajes @Niklasson89 Should I add one for you guys or do you wish to avoid it? 🙂

**Comment by Niklasson89** [comment]
@themaxsandelin Feel free to add one if you like :D
